export { Books } from './Books';
export { Contacts } from './Contacts';
export { Home } from './Home';
export { InfoBoard } from './InfoBoard';
export { Players } from './Players';
export { Ranks } from './Ranks';
export { GoStories } from './GoStories';
export { WAGC } from './WAGC';
export { WelcomeToGo } from './WelcomeToGo';